defaultPortal: developer-test-account-1
portals:
  - name: developer-test-account-1
    portalId: 242035232
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CI6byK3iMhIaAA0AQAAA4G0DQAJYAgEAAPgAAAAAAAAAAAYYoNS0cyDD7v8kKO7pDDIUnf6mdzE4L21nYDdJWozULzhUXkQ6TwAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAgAwAAAAAAPP4DAAAAAAAAAAwEAAAAAAAAAAAAABAAAMBCFNisae0T7tNG0ztzjSEZ3V6PWPxBSgNuYTJSAFoAYABow-7_JHAA
        expiresAt: '2025-04-11T16:32:28.087Z'
    accountType: DEVELOPER_TEST
    personalAccessKey: >-
      CiRuYTItNGEwYS1mMWY0LTRmZTUtOTY3ZS01NDUyMTE4MWNhZDkQoNS0cxjD7v8kKhkABeaRgrQRNC581pyFp_yksJmbogVkX3eCSgNuYTI
    parentAccountId: 242035221
